<a href="https://colab.research.google.com/github/Balu4ok/MyProject/blob/main/%D0%9B%D1%804_%D0%93%D0%B0%D1%80%D0%BA%D1%83%D1%88%D0%B0%2C_%D0%B2%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%82_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'2.0.2'

1. створи матрицю 3*3, заповни її цілими випадковими числами від 1 до 5

In [ ]:
matrix = np.random.randint(1, 6, size=(3, 3))

matrix

array([[4, 1, 4],
       [2, 2, 1],
       [2, 1, 2]])

2. обчислити визначник матриці


In [ ]:
det = np.linalg.det(matrix)
det

np.float64(1.9999999999999993)

3. знайти добуток всіх елементів матриці

In [ ]:
product = np.prod(matrix)
product

np.int64(256)

In [ ]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(256)

4. знайти суму всіх елементів матриці

In [ ]:
sum_1 = np.sum(matrix)

sum_1

np.int64(19)

5. обчислити найбільший, найменший елементи

In [ ]:
#Скорочений запис
np.max(matrix)

np.int64(4)

In [ ]:
#Скорочений запис
np.min(matrix)

np.int64(1)

In [ ]:
np.mean(matrix)

np.float64(2.111111111111111)

In [ ]:
mean = np.mean(matrix)
print("середнє значення елементів матриці:", mean)

середнє значення елементів матриці: 2.111111111111111


знайти матрицю, що складена з квадратних коренів

In [ ]:
np.sqrt(matrix)

array([[2.        , 1.        , 2.        ],
       [1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.        , 1.41421356]])

In [ ]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)

print("сума елементів кожного рядка")
print(row_sums)
#в результаті отримали вектор - стовпчик

сума елементів кожного рядка
[[9]
 [5]
 [5]]


In [ ]:
vector = np.random.randint(0, 10, size=25)
vector

array([0, 4, 8, 6, 3, 6, 0, 8, 1, 0, 6, 7, 5, 5, 8, 7, 3, 3, 3, 0, 1, 5,
       4, 3, 6])

In [ ]:
sorted_vector = np.sort(vector)[::-1]
sorted_vector

array([8, 8, 8, 7, 7, 6, 6, 6, 6, 5, 5, 5, 4, 4, 3, 3, 3, 3, 3, 1, 1, 0,
       0, 0, 0])

In [ ]:
a = np.array([[7, 3, -6], [7, 9, -9], [2, -4, 9]])
b = np.array([-1, 5, 28])

x = np.linalg.solve(a, b)
print('Вбудована функція', x)

inv_a = np.linalg.inv(a)
x1 = inv_a.dot(b)
print('Матричний метод', x1)

Вбудована функція [2. 3. 4.]
Матричний метод [2. 3. 4.]


In [ ]:
#метод Крамера
def kramer(a, b):
    det_a = np.linalg.det(a)
    if det_a != 0:
        solutions = []
        for i in range(len(a)):
            modified_a = np.copy(a)
            modified_a[:, i] = b
            solutions.append(round(np.linalg.det(modified_a) / det_a, 1))

        print('Solving a system of linear algebraic equations by Cramer\'s method:')
        #print('x =', solutions)

    else:
        print('Determinant equals zero, the system has no solutions')
    return solutions
# Виклик функцій для розв'язання системи
print(kramer(a, b))

Solving a system of linear algebraic equations by Cramer's method:
[np.float64(2.0), np.float64(3.0), np.float64(4.0)]
